In [1]:
import numpy as np

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

np.int64(0)

In [13]:
#can use slice notation (start:end)
arr[1:5]

array([1, 2, 3, 4])

In [14]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [15]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [16]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [17]:
#Can broadcast arrays
arr[0:5] = 100

In [18]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
arr = np.arange(0,11)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
slice_of_arr = arr[0:6]

In [22]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [23]:
slice_of_arr[:] = 99

In [24]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#Copy an array to a variable
arr_copy = arr.copy()

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_copy[:] = 100

In [30]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [31]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#Same as double bracket notation [0][1]
arr_2d[2,1]

array([40, 45])

In [39]:
#To get chunks you use the slice notation
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
arr_2d[1:2]

array([[20, 25, 30]])

In [46]:
arr = np.arange(1,11)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
#Return an array of boolean values
bool_arr = arr > 5

In [51]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
#Using a boolean array to conditionally show values that are true
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [53]:
arr[arr<3]

array([1, 2])

In [54]:
arr_2d = np.arange(50).reshape(5,10)

In [55]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])