In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [ ]:
#Cast a normal list into an array
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat =[[1,2,3], [4,5,6], [7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#Similar to range function but for arrays
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#Brings evenly spaced points between two numbers
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
#Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.51091725, 0.73791805, 0.39440761, 0.4043024 , 0.67411737])

In [ ]:
#5x5 matrix of random numbers from a uniform distribution from 0 to 1
np.random.rand(5,5)

array([[0.07126175, 0.88066498, 0.54175578, 0.71653999, 0.13233533],
       [0.49408832, 0.91183345, 0.3271574 , 0.95058157, 0.85333398],
       [0.71477494, 0.56733047, 0.1833853 , 0.6976565 , 0.57620581],
       [0.31995146, 0.57381244, 0.6189802 , 0.5519005 , 0.14286332],
       [0.47686668, 0.46178115, 0.39725266, 0.34857452, 0.74118068]])

In [32]:
np.random.randn(4,4)

array([[ 0.74785424,  0.42860166,  0.6245252 ,  0.6319325 ],
       [ 1.01298871, -0.20575119, -0.74179716,  0.61322905],
       [-0.32222377, -0.46539136, -1.08395858, -2.71778329],
       [ 0.17134103, -0.96559826,  0.41679347, -1.04547616]])

In [35]:
#Random integer between two numbers and how many you want
np.random.randint(1,100,10)

array([32, 11,  5, 15, 71, 73, 21, 32, 58, 85], dtype=int32)

In [36]:
arr = np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
ranarr = np.random.randint(0, 50, 10)

In [39]:
ranarr

array([24, 36, 35,  6, 46, 37, 41, 42, 19,  5], dtype=int32)

In [43]:
#Reshape method to reshape an array matrix
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#Get Max value of array
ranarr.max()

np.int32(46)

In [46]:
#Get Min value of array
ranarr.min()

np.int32(5)

In [47]:
ranarr

array([24, 36, 35,  6, 46, 37, 41, 42, 19,  5], dtype=int32)

In [ ]:
#Returns index of max value of array
ranarr.argmax()

np.int64(4)

In [ ]:
#Returns index of min value of array
ranarr.argmin()

np.int64(9)

In [ ]:
#One dimensional matrix
arr.shape

(25,)

In [51]:
arr = arr.reshape(5,5)

In [ ]:
#Two dimensional
arr.shape

(5, 5)

In [53]:
arr.dtype

dtype('int64')

In [54]:
from numpy.random import randint

In [55]:
randint(2,10)

4